name: Build macOS ARM64 VST3

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure ARM64
        run: cmake -B build -S . -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload VST3
        uses: actions/upload-artifact@v4
        with:
          name: D7S-VST3-Mac-ARM64
          path: build/**/*.vst3
